In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else :
  print("GPU not available. Using CPU.")

GPU is available
Using GPU : Tesla T4


Creating a Tensor

In [3]:
# using empty
a = torch.empty(2,3)


In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2,3)

tensor([[0.7557, 0.6878, 0.8950],
        [0.9070, 0.9466, 0.1295]])

In [8]:
# using of seed
torch.rand(2,3)

tensor([[0.8479, 0.6924, 0.1079],
        [0.5445, 0.6826, 0.1262]])

In [9]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3,3),5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [17]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
x.shape

torch.Size([2, 3])

In [19]:
torch.empty_like(x)

tensor([[             293994,                  78,                   0],
        [                  0,                   0, 8319683848551211643]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [22]:
torch.rand_like(x, dtype = torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Tensor Data Types

In [24]:
# find data type
x.dtype

torch.int64

In [26]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [27]:
torch.tensor([1,2,3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [29]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical operations

1. Scalar operation

In [31]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [33]:
# addition
x + 2
# substraction
x-2
# multiplication
x*3
# division
x/3
# int division
(x*100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

2. Element wise operation

In [35]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print (a)
print (b)

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])
tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])


In [36]:
# add
a + b
# sub
a-b
# multiply
a*b
# division
a/b
# power
a**b
# mod
a%b

tensor([[0.0060, 0.0377, 0.5277],
        [0.2472, 0.1394, 0.4235]])

In [37]:
c = torch.tensor([1,-2,3,-4])

In [38]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [39]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [40]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [41]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [42]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [43]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [44]:
# clamp
torch.clamp(d, min =2, max =3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

3. Reduction operation

In [45]:
e = torch.randint(size = (2,3), low =0, high =10, dtype=torch.float32)
e

tensor([[5., 7., 5.],
        [9., 9., 7.]])

In [46]:
# sum
torch.sum(e)

tensor(42.)

In [47]:
# sum along columns
torch.sum(e, dim =0)

tensor([14., 16., 12.])

In [49]:
# sum along rows
torch.sum(e, dim =1)

tensor([17., 25.])

In [50]:
# mean
torch.mean(e)

tensor(7.)

In [51]:
# mean along col
torch.mean(e, dim =0)

tensor([7., 8., 6.])

In [52]:
# median
torch.median(e)

tensor(7.)

In [54]:
# max and min
torch.max(e)
torch.min(e)

tensor(5.)

In [55]:
# product
torch.prod(e)

tensor(99225.)

In [56]:
# standard deviation
torch.std(e)

tensor(1.7889)

In [57]:
# variance
torch.var(e)

tensor(3.2000)

In [58]:
# argmax
torch.argmax(e)

tensor(3)

In [59]:
# argmin
torch.argmin(e)

tensor(0)

4. Matrix operations


In [61]:
f = torch.randint(size = (2,3), low =0, high =10)
g = torch.randint(size = (3,2), low =0, high=10)

print(f)
print(g)

tensor([[6, 1, 5],
        [5, 0, 4]])
tensor([[3, 8],
        [8, 3],
        [3, 5]])


In [62]:
# matrix multiplicaion
torch.matmul(f,g)

tensor([[41, 76],
        [27, 60]])

In [63]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

#dot product
torch.dot(vector1, vector2)

tensor(11)

In [64]:
#transpose
torch.transpose(f,0,1)

tensor([[6, 5],
        [1, 0],
        [5, 4]])

In [65]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 6., 4.],
        [0., 8., 4.],
        [7., 2., 3.]])

In [66]:
# determinant
torch.det(h)

tensor(-56.0000)

In [67]:
# inverse
torch.inverse(h)

tensor([[-0.2857,  0.1786,  0.1429],
        [-0.5000,  0.5000,  0.0000],
        [ 1.0000, -0.7500,  0.0000]])

5. Comparison operations

In [68]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[8, 5, 6],
        [2, 9, 5]])
tensor([[0, 4, 2],
        [7, 1, 1]])


In [69]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

6. Special functions


In [70]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 4., 4.],
        [1., 1., 2.]])

In [71]:
#log
torch.log(k)

tensor([[1.6094, 1.3863, 1.3863],
        [0.0000, 0.0000, 0.6931]])

In [72]:
# exp
torch.exp(k)

tensor([[148.4132,  54.5981,  54.5981],
        [  2.7183,   2.7183,   7.3891]])

In [73]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 2.0000, 2.0000],
        [1.0000, 1.0000, 1.4142]])

In [74]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.9820, 0.9820],
        [0.7311, 0.7311, 0.8808]])

In [75]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9820, 0.9526, 0.8808],
        [0.0180, 0.0474, 0.1192]])

In [76]:
# relu
torch.relu(k)

tensor([[5., 4., 4.],
        [1., 1., 2.]])

# Inplace Operations

In [77]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])
tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])


In [78]:
m.add_(n)

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [79]:
m

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [80]:
n

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [81]:
torch.relu(m)

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [82]:
m.relu_()

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [83]:
m

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [84]:
n

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

# Copying a Tensor

In [85]:
a = torch.rand(2,3)
a

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [86]:
b = a

In [87]:
b

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [88]:
a[0][0] = 0

In [89]:
a

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [90]:
b

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [91]:
id(a)

132526531208576

In [92]:
id(b)

132526531208576

In [93]:
b = a.clone()

In [94]:
a

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [95]:
b

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [96]:
a[0][0] = 10

In [97]:
a

tensor([[10.0000,  0.0887,  0.4890],
        [ 0.5887,  0.7340,  0.8497]])

In [98]:
b

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [99]:
id(a)

132526531208576

In [100]:
id(b)

132526531092928

# Tensor Operations on GPU

In [101]:
torch.cuda.is_available()

True

In [107]:
device = torch.device('cuda')

In [108]:
# creating a new tensor on GPU
torch.rand((2,3), device = device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [109]:
# moving an existing tensor to GPU
c

tensor([ 1, -2,  3, -4])

In [111]:
z = c.to(device)

In [112]:
z

tensor([ 1, -2,  3, -4], device='cuda:0')

In [105]:
import torch
import time

In [113]:
# define the size of the matrices
size = 10000 # Large size for performance comparison

# create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

#measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"time on cpu: {cpu_time:.4f}seconds")

matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

#measure time on gpu
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time

print(f"time on gpu: {gpu_time:.4f} seconds")



time on cpu: 17.9934seconds
time on gpu: 0.6821 seconds


In [114]:
#compare results
print("\nSpeedup(CPU TIME/ GPU TIME):", cpu_time/ gpu_time)


Speedup(CPU TIME/ GPU TIME): 26.381357072720224


# Reshaping Tensors

In [118]:
# reshape
a = torch.ones(4,4)
a


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [119]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [120]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [121]:
b = torch.rand(2,3,4)

In [122]:
b

tensor([[[0.2693, 0.8009, 0.5839, 0.0061],
         [0.4671, 0.8243, 0.2861, 0.7459],
         [0.8487, 0.4059, 0.2883, 0.2220]],

        [[0.6423, 0.7098, 0.5644, 0.4549],
         [0.0729, 0.8535, 0.9793, 0.0611],
         [0.1162, 0.7666, 0.8801, 0.4203]]])

In [124]:
#permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [125]:
#unsqueeze
c = torch.rand(226,226,3)

In [126]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [128]:
# squeeze
d = torch.rand(1,20)

In [130]:
d.squeeze(0).shape

torch.Size([20])

# NumPy and PyTorch

In [131]:
import numpy as np

In [132]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [133]:
b = a.numpy()

In [134]:
b

array([1, 2, 3])

In [135]:
type(b)

numpy.ndarray

In [136]:
v = np.array([1,2,3])

In [138]:
v

array([1, 2, 3])

In [140]:
torch.from_numpy(v)

tensor([1, 2, 3])